Finschia/wasmvm

.cargo/config.toml, .github/workflows/builds_and_tests.yml, Makefile, builders/Dockerfile.alpine, builders/Dockerfile.centos7, builders/Dockerfile.cross, builders/guest/build_linux.sh, builders/guest/build_macos.sh, builders/guest/build_muslc.sh
Removes the private repo dependencies and CI configs
=> chore: remove private repo dependencies

Cargo.toml, Makefile, api/link_muslc.go, api/link_static.go, api/link_std.go, api/mocks.go, builders/Dockerfile.alpine, builders/Dockerfile.centos7, builders/Dockerfile.cross, builders/Dockerfile.static, builders/guest/build_linux_static.sh, builders/guest/build_muslc.sh, ibc_test.go, lib_test.go
This PR adds an option to link wasmvm statically on the consumer side.
(By adding build tag `static`)
- add an option to link statically
- add shared and static libs to `api/.`
=> feat: add static linking of wasmvm

.gitignore, Makefile, api/link_muslc.go, api/link_static.go, api/link_std.go, builders/Dockerfile.alpine, builders/Dockerfile.static, builders/Makefile, builders/guest/build_linux_static.sh
change tag name for static build
- change tag name: muslc -> static
- unify link_muslc.go and link_static.go -> link_static.go
- update build files: Dockerfile, Makefile
=> feat: change tag name for static build

CHANGELOG.md, Cargo.lock, Cargo.toml
release v0.14.0-0.8.0
The reason for releasing a new version soon after the previous is that the previous version tag was pointed to be a wrong commit. 
I fixed it quickly but the go proxy had cached it already. (https://proxy.golang.org/)
And it generates an error continuously.
```
verifying github.com/line/wasmvm@v0.14.0-0.7.0: checksum mismatch
downloaded: h1:aLEbXswNuwVcmq4XYDrd2YTrn49X3H5qNVlBLkOyehw=
go.sum:     h1:1gxArBbo5Yjg+IQWHQHRYlMIgj2JUdPqoDzGGyL/UqM=
SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
For more information, see 'go help module-auth'.
make: *** [Makefile:120: build] Error 1
Error: Process completed with exit code 2. …
```
=> build: release v0.14.0-0.8.0

devtools/set_version.sh
Add a script for setting the version
usage:
```
Usage: devtools/set_version.sh NEW_VERSION
e.g. devtools/set_version.sh 0.8.0
```
=> chore: add script for setting version

Cargo.lock, Cargo.toml, src/api.rs
Closes https://github.com/line/cosmwasm/pull/157
- Add copying serialized data  on VM host side.
Please The dynamic_link poc PR(https://github.com/line/wasmvm/pull/55) first. This PR is based on https://github.com/line/wasmvm/pull/55.
https://github.com/line/wasmvm/pull/55 must be merged first before this PR can be reviewed.
=> feat: add copies region of args and returns between env

Cargo.lock, Cargo.toml, src/api.rs
Closes https://github.com/line/cosmwasm/pull/178
ditto. please read more detail in the above.
=> feat: add dynamic callstack for prevent the re-entrancy attack 

.github/workflows/release.yml
- version up rust
- the same as https://github.com/line/cosmwasm/pull/206.
=> ci: fix release action does not error if new tag pushing not needed

.github/workflows/builds_and_tests.yml, .github/workflows/release.yml, api/callbacks.go, api/memory_test.go, builders/Dockerfile.alpine
Closes #69 
Release test result: https://github.com/shiki-tak/wasmvm/releases/tag/v1.0.0-0.10.1
=> ci: add release job

Cargo.lock, Cargo.toml, src/api.rs
This PR adds env as the second argument passed to dynamic link functions.
This PR is to follow https://github.com/line/cosmwasm/pull/234.
~~After it is merged, this PR is changed and force-pushed.~~ force pushed.
=> feat: pass env as the second arg of dynamic linked callee function

api/lib_test.go, lib_test.go, libwasmvm/src/cache.rs
The `get_metrics` and `GetMetrics` test fails when the test is performed in a different environment, such as the M1 environment, so the test has been fixed.
A similar error was found in `CosmWasm/wasmvm`, so the test were fixed in the same way.
- https://github.com/CosmWasm/wasmvm/issues/340
- https://github.com/CosmWasm/wasmvm/pull/351
=> fix: getmetrics test due to this is environment-dependent test

.github/workflows/builds_and_tests.yml, CHANGELOG.md, api/callbacks.go, api/iterator.go, api/iterator_test.go, api/memory_test.go, api/mocks.go, lib.go
I add the missing codes in the previous pr #77
=> chore: remove the copied interface from tm-db

api/bindings.h, api/callbacks.go, api/callbacks_cgo.go, libwasmvm/Cargo.lock, libwasmvm/Cargo.toml, libwasmvm/bindings.h, libwasmvm/src/api.rs
This PR makes `cantract_call` costs instantiation cost to each instantiating callee VM. This is for https://github.com/line/cosmwasm/issues/257.
This PR is constructed by following 2 parts
- follow https://github.com/line/lbm-sdk/pull/835 's changing of the interface of `GetContractEnv`
- use the instantiation cost calculated by the above change to limit the input size of dynamic links
=> fix: make cantract_call costs instantiation cost to each instantiating callee VM

.github/workflows/builds_and_tests.yml, Makefile
Added .so / .dylib file that was missing from PR https://github.com/line/wasmvm/pull/84.
=> fix: add .so / .dylib file and modify Makefile

.github/workflows/release.yml
release job fixed, so re-release
test result: https://github.com/shiki-tak/wasmvm/releases
=> build: bump up v1.1.1-0.11.1

.github/workflows/builds_and_tests.yml, CHANGELOG.md, lib_test.go, libwasmvm/Cargo.lock, libwasmvm/Cargo.toml
Other service can't get the `v1.1.1-0.11.1` wasm library. 
I think it is occurred since I retag `v1.1.1-0.11.1`.
So, I add new tag (`v1.1.1-0.11.2`), but there is not a functional changes.
related: https://github.com/line/finschia/pull/153, https://github.com/line/wasmd/pull/14
* add shared libraries v1.1.1-0.11.2
* add ci test for check if the compiled shared library is correct version in `./internal/api`.
=> fix: wrong tag reference (v1.1.1-0.11.2)

libwasmvm/src/cache.rs
Without this PR, libwasmvm's test `init_cache_writes_error` fails in rustc v1.68 (stable now) or later. (#107)
This PR fixes the test for both of rustc before/after v1.68.
Closes #107
=> fix: fix a test for rustc 1.68 or later

.chglog/CHANGELOG.tpl.md, .chglog/config.yml, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, Makefile, NOTICE, README.md, builders/Makefile, cmd/demo/main.go, go.mod, ibc_test.go, internal/api/api_test.go, internal/api/callbacks.go, internal/api/iterator_test.go, internal/api/lib.go, internal/api/lib_test.go, internal/api/mocks.go, lib.go, lib_test.go, libwasmvm/Cargo.lock, libwasmvm/Cargo.toml, testdata/README.md, testdata/download_releases.sh, types/ibc.go, types/msg.go, types/queries.go
This PR
- change depending cosmwasm from line/cosmwasm to Finschia/cosmwasm
- change module name from line/wasmvm to Finschia/wasmvm
Closes #104
=> build: replace line modules with Finschia's

.github/workflows/release.yml, CHANGELOG.md, Makefile, builders/guest/build_macos_static.sh, internal/api/link_mac.go, internal/api/link_mac_static.go, libwasmvm/Cargo.toml, libwasmvm/src/examples/wasmvmstatic.rs
Add static build for macos.
Add static library for macos in release github action as release assets. The asset file of static library is `libwasmvmstatic_darwin.a` and it's a little big size. So I didn't add as github file in the `internal/api` directory.
This PR is cherry pick PR of [cosmwasm/wasmvm v1.2.1](https://github.com/CosmWasm/wasmvm/releases/tag/v1.2.1)
=> feat: Add static build for macos

internal/api/version_test.go, lib_test.go, libwasmvm/Cargo.lock, libwasmvm/Cargo.toml, libwasmvm/src/version.rs
This PR is for version bump to v1.1.1-0.11.3-rc1
=> build: version bump to 1.1.1-0.11.3-rc1

.github/workflows/release.yml, CHANGELOG.md, devtools/set_version.sh, internal/api/version_test.go, lib_test.go, libwasmvm/Cargo.lock, libwasmvm/Cargo.toml, libwasmvm/src/version.rs
The go command cannot recognize the **build metadata(+) tag**, this causes a problem in wasmd where the version check of libwasmvm cannot be done.
- https://github.com/Finschia/wasmd/blob/1eb1bbdfbb07d19152acc7f0143bb53386c54fc8/x/wasm/module.go#L271-L284
- https://github.com/Finschia/wasmd/blob/1eb1bbdfbb07d19152acc7f0143bb53386c54fc8/x/wasm/module_test.go#L590-L606
So I reverted to the previous pre-release versioning of wasmvm.
Set version to v1.1.1-0.11.6.
=> revert: use pre-release versioning and set version to 1.1.1-0.11.6

builders/Dockerfile.alpine, libwasmvm/Cargo.lock, libwasmvm/Cargo.toml
update imported cosmwasm to v1.1.9+0.9.0
=> build: update imported cosmwasm

.github/workflows/builds_and_tests.yml, .github/workflows/deploy_to_git.yml
This PR changes the trigger of the test of internal libwasmvm binaries.
This is always triggered before this PR, and this PR changes it triggered only PR by the libwasmvm build bot.
wasmvm has 2 tests for PR for the main branch, before this PR.
- Building libwasmvm binaries from the source and doing tests with it
- Doing tests with libwasmvm included in internal/api directory
An error is caused in CI when internal/api's libwasmvm is old, though we have a CI building libwasmvm binaries after the main branch is updated.
As a result, if PR publishers think that they leave building libwasmvm on CI after the merge, internal libwasmvm's test fails. (now we have this issue on https://github.com/Finschia/wasmvm/pull/142)
To solve this, we change the trigger of the test of internal/api's libwasmvm …
=> ci: change test internal libwasmvm binary triggered only build PR
